### ISSUE TITLE
IndexOf fails on NET451

### ISSUE THREAD

**Issue by mgravell** [davidfowl/Channels#64]
to repro: add net451 to Channels.Tests project.json

Result:

```
xUnit.net .NET CLI test runner (64-bit Desktop .NET win10-x64)
  Discovering: Channels.Tests
  Discovered:  Channels.Tests
  Starting:    Channels.Tests
    Channels.Tests.ChannelFacts.SlowPathIndexOfAcrossBlocks [FAIL]
      Assert.Equal() Failure
                 (pos 0)
      Expected: World
      Actual:   aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa···
                 (pos 0)
      Stack Trace:
        ChannelFacts.cs(127,0): at Channels.Tests.ChannelFacts.<SlowPathIndexOfAcrossBlocks>d__4.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Channels.Tests.ReadableBufferFacts.TestIndexOfWorksForAllLocations [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        ReadableBufferFacts.cs(161,0): at Channels.Tests.ReadableBufferFacts.TestIndexOfWorksForAllLocations(ReadableBuffer& readBuffer, Byte emptyValue)
        ReadableBufferFacts.cs(37,0): at Channels.Tests.ReadableBufferFacts.<TestIndexOfWorksForAllLocations>d__0.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  Finished:    Channels.Tests
=== TEST EXECUTION SUMMARY ===
   Channels.Tests  Total: 24, Errors: 0, Failed: 2, Skipped: 0, Time: 0.409s
SUMMARY: Total: 2 targets, Passed: 1, Failed: 1.
```

**Comment by mgravell** [comment]
Note: placeholder in case I don't get time to fix it this am; investigating
